# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CHLAValet' do
  use_frameworks!

  # Pods for CHLAValet
  pod 'Alamofire', '~> 5.0.0-beta.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SwiftSpinner'

  target 'CHLAValetTests' do
    inherit! :search_paths
  end
end
